// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type BakeryOrder struct {
	ID            uuid.UUID
	TotalAmount   float32
	PaymentMethod string
	Status        string
	UserID        uuid.UUID
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
	DeletedAt     sql.NullTime
}

type BakeryOrderProduct struct {
	OrderID   uuid.UUID
	ProductID uuid.UUID
	Price     float32
	Quantity  int32
}

type BakeryProduct struct {
	ID          uuid.UUID
	Price       string
	Name        string
	Description string
	Category    string
	Stock       int32
	Image       string
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
}

type BakeryUser struct {
	ID        uuid.UUID
	FirstName string
	LastName  string
	Email     string
	Password  string
	BirthDate time.Time
	Phone     string
	Role      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}
