// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
)

type BakeryOrder struct {
	ID            string
	TotalAmount   float64
	PaymentMethod string
	Status        string
	UserID        string
	CreatedAt     string
	UpdatedAt     string
}

type BakeryOrderProduct struct {
	OrderID         string
	ProductID       string
	ProductName     string
	ProductPrice    float64
	ProductDiscount float64
	ProductRating   float64
	TotalPrice      float64
	Quantity        int64
}

type BakeryProduct struct {
	ID          string
	Name        string
	Description string
	Category    string
	Price       float64
	Stock       int64
	Issued      int64
	HasStock    int64
	Discount    float64
	Rating      float64
	Images      string
	CreatedAt   string
	UpdatedAt   string
	DeletedAt   sql.NullString
}

type BakerySession struct {
	Token  string
	UserID string
}

type BakeryUser struct {
	ID          string
	FirstName   string
	LastName    string
	Username    string
	Email       string
	Password    string
	PhoneNumber string
	BirthDate   string
	Address1    string
	Address2    string
	Gender      string
	Role        string
	CreatedAt   string
	UpdatedAt   string
	DeletedAt   sql.NullString
}
