// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: product.sql

package database

import (
	"context"
	"database/sql"
)

const createProduct = `-- name: CreateProduct :one
;

INSERT INTO bakery_product (
    id,
    name,
    description,
    category,
    price,
    stock,
    issued,
    has_stock,
    discount,
    rating,
    images,
    created_at,
    updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, description, category, price, stock, issued, has_stock, discount, rating, images, created_at, updated_at, deleted_at
`

type CreateProductParams struct {
	ID          string
	Name        string
	Description string
	Category    string
	Price       float64
	Stock       int64
	Issued      int64
	HasStock    int64
	Discount    float64
	Rating      float64
	Images      string
	CreatedAt   string
	UpdatedAt   string
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (BakeryProduct, error) {
	row := q.db.QueryRowContext(ctx, createProduct,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.Price,
		arg.Stock,
		arg.Issued,
		arg.HasStock,
		arg.Discount,
		arg.Rating,
		arg.Images,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i BakeryProduct
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.Price,
		&i.Stock,
		&i.Issued,
		&i.HasStock,
		&i.Discount,
		&i.Rating,
		&i.Images,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
UPDATE bakery_product SET 
    deleted_at = ?
WHERE id = ?
`

type DeleteProductParams struct {
	DeletedAt sql.NullString
	ID        string
}

func (q *Queries) DeleteProduct(ctx context.Context, arg DeleteProductParams) error {
	_, err := q.db.ExecContext(ctx, deleteProduct, arg.DeletedAt, arg.ID)
	return err
}

const getProductById = `-- name: GetProductById :one
;

select id, name, description, category, price, stock, issued, has_stock, discount, rating, images, created_at, updated_at, deleted_at
from bakery_product
where bakery_product.id = ? and bakery_product.deleted_at is null
`

func (q *Queries) GetProductById(ctx context.Context, id string) (BakeryProduct, error) {
	row := q.db.QueryRowContext(ctx, getProductById, id)
	var i BakeryProduct
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.Price,
		&i.Stock,
		&i.Issued,
		&i.HasStock,
		&i.Discount,
		&i.Rating,
		&i.Images,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProducts = `-- name: GetProducts :many
select id, name, description, category, price, stock, issued, has_stock, discount, rating, images, created_at, updated_at, deleted_at
from bakery_product
where bakery_product.deleted_at is null
`

func (q *Queries) GetProducts(ctx context.Context) ([]BakeryProduct, error) {
	rows, err := q.db.QueryContext(ctx, getProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BakeryProduct
	for rows.Next() {
		var i BakeryProduct
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.Price,
			&i.Stock,
			&i.Issued,
			&i.HasStock,
			&i.Discount,
			&i.Rating,
			&i.Images,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE bakery_product SET
    description = ?,
    category = ?,
    price = ?,
    stock = ?,
    issued = ?,
    has_stock = ?,
    discount = ?,
    rating = ?,
    images = ?,
    updated_at = ?
WHERE id = ?
RETURNING id, name, description, category, price, stock, issued, has_stock, discount, rating, images, created_at, updated_at, deleted_at
`

type UpdateProductParams struct {
	Description string
	Category    string
	Price       float64
	Stock       int64
	Issued      int64
	HasStock    int64
	Discount    float64
	Rating      float64
	Images      string
	UpdatedAt   string
	ID          string
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (BakeryProduct, error) {
	row := q.db.QueryRowContext(ctx, updateProduct,
		arg.Description,
		arg.Category,
		arg.Price,
		arg.Stock,
		arg.Issued,
		arg.HasStock,
		arg.Discount,
		arg.Rating,
		arg.Images,
		arg.UpdatedAt,
		arg.ID,
	)
	var i BakeryProduct
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.Price,
		&i.Stock,
		&i.Issued,
		&i.HasStock,
		&i.Discount,
		&i.Rating,
		&i.Images,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
